openapi: 3.0.0
info:
  title: RAG Chatbot API
  version: 1.0.0
  description: API for the Retrieval-Augmented Generation (RAG) Chatbot, allowing users to query book content.

servers:
  - url: http://localhost:8080/api/v1
    description: Local Development Server

paths:
  /query:
    post:
      summary: Submit a user query to the RAG chatbot
      operationId: submitQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's natural language query.
          example: "What are the main components of ROS 2?"

    QueryResponse:
      type: object
      required:
        - answer
        - sources
      properties:
        answer:
          type: string
          description: The generated answer from the RAG chatbot, based on book content.
          example: "ROS 2 consists of nodes, topics, services, and parameters for distributed robotics control."
        sources:
          type: array
          description: List of source documents (e.g., book chapters, modules) used to generate the answer.
          items:
            type: string
          example: ["module1/1.2-nodes-topics-services.md", "module1/1.3-rclpy.md"]

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: A unique error code.
          example: "INVALID_QUERY"
        message:
          type: string
          description: A human-readable error message.
          example: "Query is too long or empty."
